### ISSUE TITLE
画像アップロード機能

### ISSUE THREAD

**Issue by ywenli** [ywenli/techpit-match#4]
# これは？

画像をアップロードできる機能を追加します。

## todo

- [x] gemの導入 carrierwave, mini_magick
- [x] uploaderファイルを追加する
- [x] user.rbにmount_uploaderを追加
- [x] img_name_uploader.rbを編集

## 備考

なし
